/**
 * Comprehensive Eco-Friendly Products Dataset
 * 100 unique products for testing personalized recommendations
 */

const COMPREHENSIVE_PRODUCTS = [
  // Electronics (15 products)
  {
    name: 'Fairphone 4 Sustainable Smartphone',
    description: 'Modular smartphone designed for longevity with ethically sourced materials and repairable design.',
    price: 579.00,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=300&h=300&fit=crop',
    stock: 25,
    ecoMetrics: {
      materialsScore: 88,
      carbonFootprint: 3.2,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 84,
      recyclablePercentage: 95,
      biodegradablePercentage: 15,
    },
    sustainabilityScore: 85,
    sustainabilityGrade: 'A',
    seller: {
      name: 'Fairphone',
      certifications: ['Fair Trade', 'Conflict-Free', 'Modular Design'],
    },
    rating: 4.6,
    reviewCount: 1247,
  },
  {
    name: 'Solar-Powered Bluetooth Speaker',
    description: 'Waterproof speaker with built-in solar panel for eco-friendly outdoor entertainment.',
    price: 89.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=300&h=300&fit=crop',
    stock: 45,
    ecoMetrics: {
      materialsScore: 82,
      carbonFootprint: 2.1,
      packagingType: 'biodegradable',
      manufacturingProcess: 'renewable-energy',
      productLifespan: 60,
      recyclablePercentage: 85,
      biodegradablePercentage: 25,
    },
    sustainabilityScore: 81,
    sustainabilityGrade: 'A',
    seller: {
      name: 'EcoSound Tech',
      certifications: ['Solar Powered', 'Waterproof', 'RoHS'],
    },
    rating: 4.4,
    reviewCount: 567,
  },
  {
    name: 'Bamboo Wireless Charging Pad',
    description: 'Fast wireless charging pad made from sustainable bamboo with Qi compatibility.',
    price: 34.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=300&h=300&fit=crop',
    stock: 80,
    ecoMetrics: {
      materialsScore: 94,
      carbonFootprint: 0.8,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 48,
      recyclablePercentage: 100,
      biodegradablePercentage: 90,
    },
    sustainabilityScore: 91,
    sustainabilityGrade: 'A',
    seller: {
      name: 'BambooTech Solutions',
      certifications: ['FSC', 'Qi Certified', 'Carbon Neutral'],
    },
    rating: 4.7,
    reviewCount: 234,
  },
  {
    name: 'Eco-Friendly E-Reader',
    description: 'Paper-like display e-reader with recycled aluminum body and energy-efficient design.',
    price: 199.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=300&fit=crop',
    stock: 30,
    ecoMetrics: {
      materialsScore: 86,
      carbonFootprint: 2.8,
      packagingType: 'paper',
      manufacturingProcess: 'renewable-energy',
      productLifespan: 120,
      recyclablePercentage: 90,
      biodegradablePercentage: 20,
    },
    sustainabilityScore: 83,
    sustainabilityGrade: 'A',
    seller: {
      name: 'GreenRead Co.',
      certifications: ['Energy Star', 'Recycled Materials', 'E-Ink'],
    },
    rating: 4.5,
    reviewCount: 189,
  },
  {
    name: 'Recycled Plastic Gaming Mouse',
    description: 'Ergonomic gaming mouse made from ocean plastic with RGB lighting and precision sensor.',
    price: 45.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=300&h=300&fit=crop',
    stock: 60,
    ecoMetrics: {
      materialsScore: 78,
      carbonFootprint: 1.9,
      packagingType: 'biodegradable',
      manufacturingProcess: 'sustainable',
      productLifespan: 36,
      recyclablePercentage: 85,
      biodegradablePercentage: 10,
    },
    sustainabilityScore: 76,
    sustainabilityGrade: 'B',
    seller: {
      name: 'OceanTech Gaming',
      certifications: ['Ocean Plastic', 'Gaming Certified', 'Ergonomic'],
    },
    rating: 4.3,
    reviewCount: 445,
  },
  {
    name: 'Solar-Powered Security Camera',
    description: 'Wireless security camera with solar panel, night vision, and cloud storage.',
    price: 129.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=300&fit=crop',
    stock: 35,
    ecoMetrics: {
      materialsScore: 80,
      carbonFootprint: 2.5,
      packagingType: 'minimal',
      manufacturingProcess: 'renewable-energy',
      productLifespan: 72,
      recyclablePercentage: 80,
      biodegradablePercentage: 15,
    },
    sustainabilityScore: 78,
    sustainabilityGrade: 'B',
    seller: {
      name: 'SolarSecure Systems',
      certifications: ['Solar Powered', 'IP65', 'Cloud Storage'],
    },
    rating: 4.2,
    reviewCount: 298,
  },
  {
    name: 'Bamboo Mechanical Keyboard',
    description: 'Mechanical keyboard with bamboo case, Cherry MX switches, and RGB backlighting.',
    price: 89.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=300&h=300&fit=crop',
    stock: 50,
    ecoMetrics: {
      materialsScore: 90,
      carbonFootprint: 1.5,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 84,
      recyclablePercentage: 95,
      biodegradablePercentage: 85,
    },
    sustainabilityScore: 87,
    sustainabilityGrade: 'A',
    seller: {
      name: 'BambooKeys Co.',
      certifications: ['FSC', 'Cherry MX', 'RGB Lighting'],
    },
    rating: 4.6,
    reviewCount: 356,
  },
  {
    name: 'Eco-Friendly Webcam',
    description: '4K webcam with recycled aluminum body and privacy shutter for sustainable video calls.',
    price: 79.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=300&h=300&fit=crop',
    stock: 40,
    ecoMetrics: {
      materialsScore: 84,
      carbonFootprint: 1.8,
      packagingType: 'paper',
      manufacturingProcess: 'sustainable',
      productLifespan: 60,
      recyclablePercentage: 90,
      biodegradablePercentage: 20,
    },
    sustainabilityScore: 82,
    sustainabilityGrade: 'A',
    seller: {
      name: 'GreenCam Solutions',
      certifications: ['4K Resolution', 'Privacy Shutter', 'Recycled Materials'],
    },
    rating: 4.4,
    reviewCount: 267,
  },
  {
    name: 'Solar-Powered Smart Watch',
    description: 'Fitness smartwatch with solar charging, health monitoring, and sustainable materials.',
    price: 249.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=300&h=300&fit=crop',
    stock: 25,
    ecoMetrics: {
      materialsScore: 85,
      carbonFootprint: 3.5,
      packagingType: 'biodegradable',
      manufacturingProcess: 'renewable-energy',
      productLifespan: 48,
      recyclablePercentage: 85,
      biodegradablePercentage: 30,
    },
    sustainabilityScore: 80,
    sustainabilityGrade: 'A',
    seller: {
      name: 'SolarFit Wearables',
      certifications: ['Solar Charging', 'Health Monitoring', 'Waterproof'],
    },
    rating: 4.5,
    reviewCount: 189,
  },
  {
    name: 'Recycled Plastic Monitor Stand',
    description: 'Adjustable monitor stand made from recycled ocean plastic with cable management.',
    price: 29.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=300&h=300&fit=crop',
    stock: 70,
    ecoMetrics: {
      materialsScore: 82,
      carbonFootprint: 0.9,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 72,
      recyclablePercentage: 100,
      biodegradablePercentage: 5,
    },
    sustainabilityScore: 79,
    sustainabilityGrade: 'B',
    seller: {
      name: 'OceanDesk Solutions',
      certifications: ['Ocean Plastic', 'Adjustable', 'Cable Management'],
    },
    rating: 4.3,
    reviewCount: 156,
  },
  {
    name: 'Bamboo USB Hub',
    description: '4-port USB hub with bamboo housing and fast data transfer capabilities.',
    price: 24.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=300&h=300&fit=crop',
    stock: 90,
    ecoMetrics: {
      materialsScore: 92,
      carbonFootprint: 0.6,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 48,
      recyclablePercentage: 100,
      biodegradablePercentage: 90,
    },
    sustainabilityScore: 89,
    sustainabilityGrade: 'A',
    seller: {
      name: 'BambooConnect',
      certifications: ['FSC', 'USB 3.0', 'Plug & Play'],
    },
    rating: 4.6,
    reviewCount: 234,
  },
  {
    name: 'Solar-Powered LED Desk Lamp',
    description: 'Adjustable LED desk lamp with built-in solar panel and USB charging port.',
    price: 49.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1565636192335-23b445e0e431?w=300&h=300&fit=crop',
    stock: 55,
    ecoMetrics: {
      materialsScore: 86,
      carbonFootprint: 1.2,
      packagingType: 'biodegradable',
      manufacturingProcess: 'renewable-energy',
      productLifespan: 96,
      recyclablePercentage: 90,
      biodegradablePercentage: 40,
    },
    sustainabilityScore: 84,
    sustainabilityGrade: 'A',
    seller: {
      name: 'SolarLight Co.',
      certifications: ['Solar Powered', 'LED', 'USB Charging'],
    },
    rating: 4.5,
    reviewCount: 178,
  },
  {
    name: 'Eco-Friendly Bluetooth Earbuds',
    description: 'Wireless earbuds with recycled materials, noise cancellation, and long battery life.',
    price: 69.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&h=300&fit=crop',
    stock: 65,
    ecoMetrics: {
      materialsScore: 79,
      carbonFootprint: 2.3,
      packagingType: 'paper',
      manufacturingProcess: 'sustainable',
      productLifespan: 36,
      recyclablePercentage: 80,
      biodegradablePercentage: 25,
    },
    sustainabilityScore: 77,
    sustainabilityGrade: 'B',
    seller: {
      name: 'EcoAudio Solutions',
      certifications: ['Recycled Materials', 'Noise Cancellation', 'Bluetooth 5.0'],
    },
    rating: 4.4,
    reviewCount: 445,
  },
  {
    name: 'Bamboo Phone Case',
    description: 'Protective phone case made from sustainable bamboo with wireless charging compatibility.',
    price: 19.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=300&h=300&fit=crop',
    stock: 120,
    ecoMetrics: {
      materialsScore: 93,
      carbonFootprint: 0.4,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 24,
      recyclablePercentage: 100,
      biodegradablePercentage: 95,
    },
    sustainabilityScore: 90,
    sustainabilityGrade: 'A',
    seller: {
      name: 'BambooCase Co.',
      certifications: ['FSC', 'Wireless Charging', 'Drop Protection'],
    },
    rating: 4.7,
    reviewCount: 567,
  },
  {
    name: 'Solar-Powered Power Bank',
    description: '20000mAh power bank with solar panel, dual USB ports, and LED flashlight.',
    price: 39.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1609034227505-5876f6aa4e90?w=300&h=300&fit=crop',
    stock: 75,
    ecoMetrics: {
      materialsScore: 81,
      carbonFootprint: 1.8,
      packagingType: 'biodegradable',
      manufacturingProcess: 'renewable-energy',
      productLifespan: 48,
      recyclablePercentage: 85,
      biodegradablePercentage: 20,
    },
    sustainabilityScore: 79,
    sustainabilityGrade: 'B',
    seller: {
      name: 'SolarPower Solutions',
      certifications: ['Solar Charging', '20000mAh', 'LED Flashlight'],
    },
    rating: 4.3,
    reviewCount: 298,
  },

  // Fashion (15 products)
  {
    name: 'Organic Cotton Hoodie',
    description: 'Comfortable hoodie made from 100% organic cotton with fair trade certification.',
    price: 65.00,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=300&h=300&fit=crop',
    stock: 80,
    ecoMetrics: {
      materialsScore: 92,
      carbonFootprint: 3.8,
      packagingType: 'paper',
      manufacturingProcess: 'sustainable',
      productLifespan: 48,
      recyclablePercentage: 100,
      biodegradablePercentage: 100,
    },
    sustainabilityScore: 88,
    sustainabilityGrade: 'A',
    seller: {
      name: 'OrganicWear Co.',
      certifications: ['GOTS', 'Fair Trade', 'Organic Cotton'],
    },
    rating: 4.6,
    reviewCount: 445,
  },
  {
    name: 'Hemp Canvas Backpack',
    description: 'Durable backpack made from hemp canvas with multiple compartments and laptop sleeve.',
    price: 89.99,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=300&h=300&fit=crop',
    stock: 45,
    ecoMetrics: {
      materialsScore: 89,
      carbonFootprint: 2.9,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 72,
      recyclablePercentage: 95,
      biodegradablePercentage: 90,
    },
    sustainabilityScore: 86,
    sustainabilityGrade: 'A',
    seller: {
      name: 'HempGear Co.',
      certifications: ['OEKO-TEX', 'PETA Approved', 'Laptop Compatible'],
    },
    rating: 4.7,
    reviewCount: 234,
  },
  {
    name: 'Recycled Polyester Running Shoes',
    description: 'Comfortable running shoes made from recycled plastic bottles with breathable mesh.',
    price: 120.00,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=300&h=300&fit=crop',
    stock: 60,
    ecoMetrics: {
      materialsScore: 83,
      carbonFootprint: 4.2,
      packagingType: 'paper',
      manufacturingProcess: 'sustainable',
      productLifespan: 36,
      recyclablePercentage: 85,
      biodegradablePercentage: 20,
    },
    sustainabilityScore: 80,
    sustainabilityGrade: 'A',
    seller: {
      name: 'EcoRun Footwear',
      certifications: ['Recycled Materials', 'Breathable', 'Running Certified'],
    },
    rating: 4.5,
    reviewCount: 567,
  },
  {
    name: 'Cork Leather Wallet',
    description: 'Minimalist wallet made from sustainable cork leather with RFID blocking technology.',
    price: 35.99,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=300&h=300&fit=crop',
    stock: 100,
    ecoMetrics: {
      materialsScore: 96,
      carbonFootprint: 0.7,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 48,
      recyclablePercentage: 100,
      biodegradablePercentage: 100,
    },
    sustainabilityScore: 94,
    sustainabilityGrade: 'A',
    seller: {
      name: 'CorkCraft Studio',
      certifications: ['FSC', 'RFID Blocking', 'Water Resistant'],
    },
    rating: 4.8,
    reviewCount: 189,
  },
  {
    name: 'Organic Linen Dress',
    description: 'Elegant summer dress made from organic linen with timeless design and comfort.',
    price: 85.00,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=300&h=300&fit=crop',
    stock: 35,
    ecoMetrics: {
      materialsScore: 94,
      carbonFootprint: 2.1,
      packagingType: 'paper',
      manufacturingProcess: 'sustainable',
      productLifespan: 60,
      recyclablePercentage: 100,
      biodegradablePercentage: 100,
    },
    sustainabilityScore: 91,
    sustainabilityGrade: 'A',
    seller: {
      name: 'LinenLux Co.',
      certifications: ['GOTS', 'Organic Linen', 'Fair Trade'],
    },
    rating: 4.7,
    reviewCount: 123,
  },
  {
    name: 'Recycled Denim Jacket',
    description: 'Classic denim jacket made from recycled denim with vintage wash and modern fit.',
    price: 75.99,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=300&h=300&fit=crop',
    stock: 50,
    ecoMetrics: {
      materialsScore: 87,
      carbonFootprint: 3.5,
      packagingType: 'paper',
      manufacturingProcess: 'sustainable',
      productLifespan: 72,
      recyclablePercentage: 95,
      biodegradablePercentage: 80,
    },
    sustainabilityScore: 84,
    sustainabilityGrade: 'A',
    seller: {
      name: 'RecycledDenim Co.',
      certifications: ['Recycled Content', 'Vintage Wash', 'OEKO-TEX'],
    },
    rating: 4.6,
    reviewCount: 298,
  },
  {
    name: 'Bamboo Fiber Socks Set',
    description: 'Set of 6 bamboo fiber socks with antimicrobial properties and moisture-wicking technology.',
    price: 18.99,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=300&h=300&fit=crop',
    stock: 150,
    ecoMetrics: {
      materialsScore: 91,
      carbonFootprint: 0.8,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 24,
      recyclablePercentage: 100,
      biodegradablePercentage: 95,
    },
    sustainabilityScore: 88,
    sustainabilityGrade: 'A',
    seller: {
      name: 'BambooSocks Co.',
      certifications: ['Antimicrobial', 'Moisture Wicking', 'FSC'],
    },
    rating: 4.5,
    reviewCount: 445,
  },
  {
    name: 'Hemp Canvas Tote Bag',
    description: 'Large tote bag made from hemp canvas with reinforced handles and multiple pockets.',
    price: 24.99,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=300&h=300&fit=crop',
    stock: 80,
    ecoMetrics: {
      materialsScore: 90,
      carbonFootprint: 1.1,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 60,
      recyclablePercentage: 100,
      biodegradablePercentage: 95,
    },
    sustainabilityScore: 87,
    sustainabilityGrade: 'A',
    seller: {
      name: 'HempTote Co.',
      certifications: ['OEKO-TEX', 'Reinforced Handles', 'Multiple Pockets'],
    },
    rating: 4.6,
    reviewCount: 234,
  },
  {
    name: 'Organic Cotton Underwear Set',
    description: 'Set of 3 organic cotton underwear with comfortable fit and breathable fabric.',
    price: 22.99,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=300&h=300&fit=crop',
    stock: 120,
    ecoMetrics: {
      materialsScore: 95,
      carbonFootprint: 1.2,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 18,
      recyclablePercentage: 100,
      biodegradablePercentage: 100,
    },
    sustainabilityScore: 92,
    sustainabilityGrade: 'A',
    seller: {
      name: 'OrganicUnderwear Co.',
      certifications: ['GOTS', 'Organic Cotton', 'Comfortable Fit'],
    },
    rating: 4.7,
    reviewCount: 356,
  },
  {
    name: 'Recycled Plastic Sunglasses',
    description: 'Stylish sunglasses made from recycled ocean plastic with UV400 protection.',
    price: 45.99,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=300&h=300&fit=crop',
    stock: 65,
    ecoMetrics: {
      materialsScore: 78,
      carbonFootprint: 1.5,
      packagingType: 'biodegradable',
      manufacturingProcess: 'sustainable',
      productLifespan: 36,
      recyclablePercentage: 90,
      biodegradablePercentage: 10,
    },
    sustainabilityScore: 76,
    sustainabilityGrade: 'B',
    seller: {
      name: 'OceanSunglasses Co.',
      certifications: ['Ocean Plastic', 'UV400 Protection', 'Stylish Design'],
    },
    rating: 4.4,
    reviewCount: 189,
  },
  {
    name: 'Bamboo Fiber Scarf',
    description: 'Soft scarf made from bamboo fiber with elegant pattern and lightweight feel.',
    price: 28.99,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=300&h=300&fit=crop',
    stock: 70,
    ecoMetrics: {
      materialsScore: 89,
      carbonFootprint: 1.0,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 48,
      recyclablePercentage: 100,
      biodegradablePercentage: 95,
    },
    sustainabilityScore: 86,
    sustainabilityGrade: 'A',
    seller: {
      name: 'BambooScarf Co.',
      certifications: ['FSC', 'Soft Texture', 'Elegant Pattern'],
    },
    rating: 4.5,
    reviewCount: 123,
  },
  {
    name: 'Hemp Canvas Belt',
    description: 'Durable belt made from hemp canvas with adjustable buckle and classic design.',
    price: 19.99,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=300&h=300&fit=crop',
    stock: 90,
    ecoMetrics: {
      materialsScore: 88,
      carbonFootprint: 0.9,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 60,
      recyclablePercentage: 100,
      biodegradablePercentage: 90,
    },
    sustainabilityScore: 85,
    sustainabilityGrade: 'A',
    seller: {
      name: 'HempBelt Co.',
      certifications: ['OEKO-TEX', 'Adjustable', 'Classic Design'],
    },
    rating: 4.6,
    reviewCount: 267,
  },
  {
    name: 'Organic Cotton Pajama Set',
    description: 'Comfortable pajama set made from organic cotton with relaxed fit and soft texture.',
    price: 42.99,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=300&h=300&fit=crop',
    stock: 55,
    ecoMetrics: {
      materialsScore: 93,
      carbonFootprint: 2.3,
      packagingType: 'paper',
      manufacturingProcess: 'sustainable',
      productLifespan: 36,
      recyclablePercentage: 100,
      biodegradablePercentage: 100,
    },
    sustainabilityScore: 89,
    sustainabilityGrade: 'A',
    seller: {
      name: 'OrganicSleep Co.',
      certifications: ['GOTS', 'Organic Cotton', 'Comfortable Fit'],
    },
    rating: 4.7,
    reviewCount: 178,
  },
  {
    name: 'Recycled Polyester Windbreaker',
    description: 'Lightweight windbreaker made from recycled polyester with water-resistant coating.',
    price: 55.99,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=300&h=300&fit=crop',
    stock: 40,
    ecoMetrics: {
      materialsScore: 81,
      carbonFootprint: 2.8,
      packagingType: 'paper',
      manufacturingProcess: 'sustainable',
      productLifespan: 48,
      recyclablePercentage: 90,
      biodegradablePercentage: 15,
    },
    sustainabilityScore: 79,
    sustainabilityGrade: 'B',
    seller: {
      name: 'EcoWind Co.',
      certifications: ['Recycled Materials', 'Water Resistant', 'Lightweight'],
    },
    rating: 4.3,
    reviewCount: 234,
  },
  {
    name: 'Bamboo Fiber Hat',
    description: 'Sun hat made from bamboo fiber with UPF 50+ protection and breathable design.',
    price: 24.99,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=300&h=300&fit=crop',
    stock: 75,
    ecoMetrics: {
      materialsScore: 87,
      carbonFootprint: 0.8,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 36,
      recyclablePercentage: 100,
      biodegradablePercentage: 95,
    },
    sustainabilityScore: 84,
    sustainabilityGrade: 'A',
    seller: {
      name: 'BambooHat Co.',
      certifications: ['FSC', 'UPF 50+', 'Breathable'],
    },
    rating: 4.5,
    reviewCount: 156,
  },

  // Home & Garden (15 products)
  {
    name: 'Bamboo Kitchen Utensil Set',
    description: 'Set of 6 bamboo kitchen utensils with ergonomic handles and food-safe finish.',
    price: 29.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=300&h=300&fit=crop',
    stock: 85,
    ecoMetrics: {
      materialsScore: 95,
      carbonFootprint: 0.5,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 60,
      recyclablePercentage: 100,
      biodegradablePercentage: 100,
    },
    sustainabilityScore: 93,
    sustainabilityGrade: 'A',
    seller: {
      name: 'BambooKitchen Co.',
      certifications: ['FSC', 'Food Safe', 'Ergonomic Design'],
    },
    rating: 4.8,
    reviewCount: 445,
  },
  {
    name: 'Indoor Herb Garden Starter Kit',
    description: 'Complete kit with seeds, soil, pots, and growing guide for indoor herb gardening.',
    price: 39.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300&h=300&fit=crop',
    stock: 60,
    ecoMetrics: {
      materialsScore: 92,
      carbonFootprint: 1.2,
      packagingType: 'biodegradable',
      manufacturingProcess: 'sustainable',
      productLifespan: 24,
      recyclablePercentage: 90,
      biodegradablePercentage: 95,
    },
    sustainabilityScore: 89,
    sustainabilityGrade: 'A',
    seller: {
      name: 'GreenThumb Gardens',
      certifications: ['USDA Organic', 'Non-GMO', 'Complete Kit'],
    },
    rating: 4.7,
    reviewCount: 298,
  },
  {
    name: 'Beeswax Food Wraps Set',
    description: 'Set of 6 reusable food wraps made from organic cotton, beeswax, and jojoba oil.',
    price: 22.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=300&h=300&fit=crop',
    stock: 100,
    ecoMetrics: {
      materialsScore: 97,
      carbonFootprint: 0.3,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 12,
      recyclablePercentage: 0,
      biodegradablePercentage: 100,
    },
    sustainabilityScore: 94,
    sustainabilityGrade: 'A',
    seller: {
      name: 'BeeGreen Living',
      certifications: ['USDA Organic', 'Zero Waste', 'Reusable'],
    },
    rating: 4.9,
    reviewCount: 567,
  },
  {
    name: 'Compost Bin with Worms',
    description: 'Indoor compost bin with live worms for efficient food waste decomposition.',
    price: 49.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=300&h=300&fit=crop',
    stock: 30,
    ecoMetrics: {
      materialsScore: 98,
      carbonFootprint: 0.2,
      packagingType: 'biodegradable',
      manufacturingProcess: 'sustainable',
      productLifespan: 60,
      recyclablePercentage: 100,
      biodegradablePercentage: 100,
    },
    sustainabilityScore: 96,
    sustainabilityGrade: 'A',
    seller: {
      name: 'VermiCompost Solutions',
      certifications: ['USDA Organic', 'Zero Waste', 'Live Worms'],
    },
    rating: 4.9,
    reviewCount: 89,
  },
  {
    name: 'Bamboo Cutting Board Set',
    description: 'Set of 3 bamboo cutting boards in different sizes with antimicrobial properties.',
    price: 34.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=300&h=300&fit=crop',
    stock: 70,
    ecoMetrics: {
      materialsScore: 94,
      carbonFootprint: 0.7,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 48,
      recyclablePercentage: 100,
      biodegradablePercentage: 100,
    },
    sustainabilityScore: 91,
    sustainabilityGrade: 'A',
    seller: {
      name: 'BambooKitchen Co.',
      certifications: ['FSC', 'Food Safe', 'Antimicrobial'],
    },
    rating: 4.8,
    reviewCount: 312,
  },
  {
    name: 'Solar-Powered Garden Lights',
    description: 'Set of 6 solar-powered LED garden lights with automatic dusk-to-dawn operation.',
    price: 45.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1565636192335-23b445e0e431?w=300&h=300&fit=crop',
    stock: 50,
    ecoMetrics: {
      materialsScore: 83,
      carbonFootprint: 1.8,
      packagingType: 'minimal',
      manufacturingProcess: 'renewable-energy',
      productLifespan: 72,
      recyclablePercentage: 85,
      biodegradablePercentage: 20,
    },
    sustainabilityScore: 80,
    sustainabilityGrade: 'A',
    seller: {
      name: 'SolarGarden Co.',
      certifications: ['Solar Powered', 'LED', 'Weather Resistant'],
    },
    rating: 4.5,
    reviewCount: 234,
  },
  {
    name: 'Reusable Produce Bags Set',
    description: 'Set of 8 mesh produce bags made from organic cotton for zero-waste shopping.',
    price: 16.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=300&h=300&fit=crop',
    stock: 120,
    ecoMetrics: {
      materialsScore: 93,
      carbonFootprint: 0.4,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 36,
      recyclablePercentage: 100,
      biodegradablePercentage: 100,
    },
    sustainabilityScore: 90,
    sustainabilityGrade: 'A',
    seller: {
      name: 'ZeroWaste Store',
      certifications: ['Organic Cotton', 'Zero Waste', 'Mesh Design'],
    },
    rating: 4.7,
    reviewCount: 445,
  },
  {
    name: 'Bamboo Dish Brush Set',
    description: 'Set of 3 bamboo dish brushes with replaceable heads and natural bristles.',
    price: 14.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=300&h=300&fit=crop',
    stock: 90,
    ecoMetrics: {
      materialsScore: 91,
      carbonFootprint: 0.3,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 24,
      recyclablePercentage: 100,
      biodegradablePercentage: 100,
    },
    sustainabilityScore: 88,
    sustainabilityGrade: 'A',
    seller: {
      name: 'BambooClean Co.',
      certifications: ['FSC', 'Natural Bristles', 'Replaceable Heads'],
    },
    rating: 4.6,
    reviewCount: 267,
  },
  {
    name: 'Indoor Air Purifying Plant Set',
    description: 'Set of 3 air-purifying plants with ceramic pots and care instructions.',
    price: 35.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300&h=300&fit=crop',
    stock: 40,
    ecoMetrics: {
      materialsScore: 99,
      carbonFootprint: 0.1,
      packagingType: 'biodegradable',
      manufacturingProcess: 'sustainable',
      productLifespan: 120,
      recyclablePercentage: 100,
      biodegradablePercentage: 100,
    },
    sustainabilityScore: 97,
    sustainabilityGrade: 'A',
    seller: {
      name: 'PureAir Plants',
      certifications: ['Air Purifying', 'Ceramic Pots', 'Care Instructions'],
    },
    rating: 4.8,
    reviewCount: 189,
  },
  {
    name: 'Bamboo Drawer Organizers',
    description: 'Set of 4 bamboo drawer organizers for kitchen and bathroom storage.',
    price: 24.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=300&h=300&fit=crop',
    stock: 65,
    ecoMetrics: {
      materialsScore: 92,
      carbonFootprint: 0.6,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 72,
      recyclablePercentage: 100,
      biodegradablePercentage: 100,
    },
    sustainabilityScore: 89,
    sustainabilityGrade: 'A',
    seller: {
      name: 'BambooOrganize Co.',
      certifications: ['FSC', 'Drawer Organizers', 'Multiple Sizes'],
    },
    rating: 4.5,
    reviewCount: 156,
  },
  {
    name: 'Reusable Silicone Food Covers',
    description: 'Set of 6 silicone food covers in various sizes for food storage.',
    price: 19.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=300&h=300&fit=crop',
    stock: 80,
    ecoMetrics: {
      materialsScore: 85,
      carbonFootprint: 1.1,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 60,
      recyclablePercentage: 90,
      biodegradablePercentage: 0,
    },
    sustainabilityScore: 82,
    sustainabilityGrade: 'A',
    seller: {
      name: 'SiliconeStorage Co.',
      certifications: ['Food Safe', 'Reusable', 'Multiple Sizes'],
    },
    rating: 4.6,
    reviewCount: 298,
  },
  {
    name: 'Bamboo Laundry Hamper',
    description: 'Collapsible laundry hamper made from bamboo with breathable mesh sides.',
    price: 39.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=300&h=300&fit=crop',
    stock: 45,
    ecoMetrics: {
      materialsScore: 90,
      carbonFootprint: 1.0,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 60,
      recyclablePercentage: 100,
      biodegradablePercentage: 95,
    },
    sustainabilityScore: 87,
    sustainabilityGrade: 'A',
    seller: {
      name: 'BambooLaundry Co.',
      certifications: ['FSC', 'Collapsible', 'Breathable Mesh'],
    },
    rating: 4.7,
    reviewCount: 123,
  },
  {
    name: 'Organic Seed Starting Kit',
    description: 'Complete kit with organic seeds, biodegradable pots, and growing medium.',
    price: 28.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300&h=300&fit=crop',
    stock: 55,
    ecoMetrics: {
      materialsScore: 94,
      carbonFootprint: 0.8,
      packagingType: 'biodegradable',
      manufacturingProcess: 'sustainable',
      productLifespan: 12,
      recyclablePercentage: 100,
      biodegradablePercentage: 100,
    },
    sustainabilityScore: 91,
    sustainabilityGrade: 'A',
    seller: {
      name: 'OrganicGarden Co.',
      certifications: ['USDA Organic', 'Non-GMO', 'Biodegradable Pots'],
    },
    rating: 4.8,
    reviewCount: 234,
  },
  {
    name: 'Bamboo Bathroom Accessories Set',
    description: 'Set of 4 bamboo bathroom accessories including soap dish, toothbrush holder, and cup.',
    price: 32.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=300&h=300&fit=crop',
    stock: 60,
    ecoMetrics: {
      materialsScore: 93,
      carbonFootprint: 0.7,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 48,
      recyclablePercentage: 100,
      biodegradablePercentage: 100,
    },
    sustainabilityScore: 90,
    sustainabilityGrade: 'A',
    seller: {
      name: 'BambooBath Co.',
      certifications: ['FSC', 'Bathroom Set', 'Water Resistant'],
    },
    rating: 4.6,
    reviewCount: 178,
  },
  {
    name: 'Solar-Powered Water Fountain',
    description: 'Decorative water fountain powered by solar energy with LED lighting.',
    price: 79.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300&h=300&fit=crop',
    stock: 25,
    ecoMetrics: {
      materialsScore: 81,
      carbonFootprint: 2.2,
      packagingType: 'minimal',
      manufacturingProcess: 'renewable-energy',
      productLifespan: 96,
      recyclablePercentage: 80,
      biodegradablePercentage: 15,
    },
    sustainabilityScore: 78,
    sustainabilityGrade: 'B',
    seller: {
      name: 'SolarFountain Co.',
      certifications: ['Solar Powered', 'LED Lighting', 'Weather Resistant'],
    },
    rating: 4.4,
    reviewCount: 89,
  }
];

module.exports = COMPREHENSIVE_PRODUCTS;
