/**
 * Mock Product Data for Eco-Lens App
 * Sprint 1 - Customer Dashboard
 */

export const CATEGORIES = [
  'Electronics',
  'Fashion',
  'Home & Garden',
  'Food & Beverages',
  'Personal Care',
  'Sports & Outdoors',
  'Books & Stationery',
  'Toys & Games',
];

export const MOCK_PRODUCTS = [
  {
    id: '1',
    name: 'Bamboo Water Bottle',
    description: 'Sustainable bamboo water bottle with stainless steel interior. BPA-free and keeps drinks cold for 24 hours or hot for 12 hours.',
    price: 24.99,
    category: 'Sports & Outdoors',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=300&h=300&fit=crop',
    stock: 50,
    ecoMetrics: {
      materialsScore: 95,
      carbonFootprint: 0.5,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 60,
      recyclablePercentage: 90,
      biodegradablePercentage: 85,
    },
    sustainabilityGrade: 'A',
    sustainabilityScore: 92,
    seller: {
      name: 'EcoLife Products',
      certifications: ['FSC', 'Carbon Neutral'],
    },
    rating: 4.8,
    reviewCount: 234,
  },
  {
    id: '2',
    name: 'Organic Cotton T-Shirt',
    description: '100% organic cotton t-shirt, ethically made with fair trade practices. Soft, breathable, and durable.',
    price: 35.00,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=300&h=300&fit=crop',
    stock: 120,
    ecoMetrics: {
      materialsScore: 90,
      carbonFootprint: 2.1,
      packagingType: 'paper',
      manufacturingProcess: 'sustainable',
      productLifespan: 36,
      recyclablePercentage: 95,
      biodegradablePercentage: 100,
    },
    sustainabilityGrade: 'A',
    sustainabilityScore: 88,
    seller: {
      name: 'Green Fashion Co.',
      certifications: ['GOTS', 'Fair Trade'],
    },
    rating: 4.6,
    reviewCount: 189,
  },
  {
    id: '3',
    name: 'Solar Power Bank',
    description: '20000mAh solar power bank with dual USB ports. Waterproof and shockproof design for outdoor adventures.',
    price: 45.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1609034227505-5876f6aa4e90?w=300&h=300&fit=crop',
    stock: 75,
    ecoMetrics: {
      materialsScore: 80,
      carbonFootprint: 3.5,
      packagingType: 'biodegradable',
      manufacturingProcess: 'renewable-energy',
      productLifespan: 48,
      recyclablePercentage: 70,
      biodegradablePercentage: 20,
    },
    sustainabilityGrade: 'B',
    sustainabilityScore: 78,
    seller: {
      name: 'TechGreen Solutions',
      certifications: ['Energy Star', 'RoHS'],
    },
    rating: 4.4,
    reviewCount: 567,
  },
  {
    id: '4',
    name: 'Recycled Plastic Yoga Mat',
    description: 'Premium yoga mat made from 100% recycled plastic bottles. Non-slip surface with excellent cushioning.',
    price: 39.99,
    category: 'Sports & Outdoors',
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=300&h=300&fit=crop',
    stock: 90,
    ecoMetrics: {
      materialsScore: 85,
      carbonFootprint: 1.8,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 60,
      recyclablePercentage: 100,
      biodegradablePercentage: 0,
    },
    sustainabilityGrade: 'B',
    sustainabilityScore: 82,
    seller: {
      name: 'EcoYoga Studio',
      certifications: ['B Corp', 'Climate Neutral'],
    },
    rating: 4.7,
    reviewCount: 432,
  },
  {
    id: '5',
    name: 'Natural Bamboo Toothbrush Set',
    description: 'Set of 4 biodegradable bamboo toothbrushes with soft BPA-free bristles. Plastic-free packaging.',
    price: 12.99,
    category: 'Personal Care',
    image: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=300&h=300&fit=crop',
    stock: 200,
    ecoMetrics: {
      materialsScore: 92,
      carbonFootprint: 0.3,
      packagingType: 'biodegradable',
      manufacturingProcess: 'sustainable',
      productLifespan: 3,
      recyclablePercentage: 95,
      biodegradablePercentage: 98,
    },
    sustainabilityGrade: 'A',
    sustainabilityScore: 90,
    seller: {
      name: 'Pure Earth Essentials',
      certifications: ['FSC', 'Cruelty Free'],
    },
    rating: 4.9,
    reviewCount: 892,
  },
  {
    id: '6',
    name: 'Reusable Beeswax Food Wraps',
    description: 'Set of 6 reusable food wraps made from organic cotton, beeswax, and jojoba oil. Alternative to plastic wrap.',
    price: 18.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=300&h=300&fit=crop',
    stock: 150,
    ecoMetrics: {
      materialsScore: 94,
      carbonFootprint: 0.4,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 12,
      recyclablePercentage: 0,
      biodegradablePercentage: 100,
    },
    sustainabilityGrade: 'A',
    sustainabilityScore: 91,
    seller: {
      name: 'Bee Green Living',
      certifications: ['USDA Organic', 'Zero Waste'],
    },
    rating: 4.8,
    reviewCount: 654,
  },
  {
    id: '7',
    name: 'LED Smart Bulb',
    description: 'Energy-efficient smart LED bulb with app control. 80% less energy consumption than traditional bulbs.',
    price: 15.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1565636192335-23b445e0e431?w=300&h=300&fit=crop',
    stock: 180,
    ecoMetrics: {
      materialsScore: 70,
      carbonFootprint: 2.0,
      packagingType: 'paper',
      manufacturingProcess: 'conventional',
      productLifespan: 120,
      recyclablePercentage: 60,
      biodegradablePercentage: 10,
    },
    sustainabilityGrade: 'C',
    sustainabilityScore: 68,
    seller: {
      name: 'SmartHome Tech',
      certifications: ['Energy Star'],
    },
    rating: 4.3,
    reviewCount: 1023,
  },
  {
    id: '8',
    name: 'Compostable Phone Case',
    description: 'Biodegradable phone case made from plant-based materials. Fully compostable at end of life.',
    price: 29.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=300&h=300&fit=crop',
    stock: 100,
    ecoMetrics: {
      materialsScore: 88,
      carbonFootprint: 0.8,
      packagingType: 'biodegradable',
      manufacturingProcess: 'sustainable',
      productLifespan: 24,
      recyclablePercentage: 0,
      biodegradablePercentage: 100,
    },
    sustainabilityGrade: 'A',
    sustainabilityScore: 87,
    seller: {
      name: 'EcoCase Co.',
      certifications: ['Certified Compostable', 'Carbon Neutral'],
    },
    rating: 4.5,
    reviewCount: 345,
  },
  {
    id: '9',
    name: 'Recycled Paper Notebook Set',
    description: 'Set of 3 notebooks made from 100% recycled paper. Eco-friendly soy-based ink printing.',
    price: 14.99,
    category: 'Books & Stationery',
    image: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=300&h=300&fit=crop',
    stock: 250,
    ecoMetrics: {
      materialsScore: 85,
      carbonFootprint: 0.6,
      packagingType: 'minimal',
      manufacturingProcess: 'sustainable',
      productLifespan: 6,
      recyclablePercentage: 100,
      biodegradablePercentage: 100,
    },
    sustainabilityGrade: 'B',
    sustainabilityScore: 84,
    seller: {
      name: 'Green Paper Co.',
      certifications: ['FSC', 'Recycled Content'],
    },
    rating: 4.6,
    reviewCount: 178,
  },
  {
    id: '10',
    name: 'Stainless Steel Straw Set',
    description: 'Reusable stainless steel straws with cleaning brush and cotton carry pouch. Dishwasher safe.',
    price: 9.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=300&h=300&fit=crop',
    stock: 300,
    ecoMetrics: {
      materialsScore: 90,
      carbonFootprint: 1.2,
      packagingType: 'minimal',
      manufacturingProcess: 'conventional',
      productLifespan: 120,
      recyclablePercentage: 100,
      biodegradablePercentage: 0,
    },
    sustainabilityGrade: 'B',
    sustainabilityScore: 81,
    seller: {
      name: 'Zero Waste Store',
      certifications: ['B Corp'],
    },
    rating: 4.7,
    reviewCount: 567,
  },
  {
    id: '11',
    name: 'Organic Fair Trade Coffee',
    description: '100% Arabica organic coffee beans, fair trade certified. Medium roast with notes of chocolate and caramel.',
    price: 16.99,
    category: 'Food & Beverages',
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=300&h=300&fit=crop',
    stock: 80,
    ecoMetrics: {
      materialsScore: 95,
      carbonFootprint: 3.2,
      packagingType: 'biodegradable',
      manufacturingProcess: 'sustainable',
      productLifespan: 1,
      recyclablePercentage: 100,
      biodegradablePercentage: 100,
    },
    sustainabilityGrade: 'A',
    sustainabilityScore: 86,
    seller: {
      name: 'Ethical Bean Co.',
      certifications: ['USDA Organic', 'Fair Trade', 'Rainforest Alliance'],
    },
    rating: 4.9,
    reviewCount: 432,
  },
  {
    id: '12',
    name: 'Hemp Backpack',
    description: 'Durable backpack made from hemp fiber. Water-resistant with multiple compartments and laptop sleeve.',
    price: 59.99,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=300&h=300&fit=crop',
    stock: 60,
    ecoMetrics: {
      materialsScore: 88,
      carbonFootprint: 2.8,
      packagingType: 'paper',
      manufacturingProcess: 'sustainable',
      productLifespan: 60,
      recyclablePercentage: 80,
      biodegradablePercentage: 90,
    },
    sustainabilityGrade: 'B',
    sustainabilityScore: 83,
    seller: {
      name: 'Hemp Goods Co.',
      certifications: ['OEKO-TEX', 'PETA Approved'],
    },
    rating: 4.4,
    reviewCount: 234,
  },
  {
    id: '13',
    name: 'Natural Rubber Flip Flops',
    description: 'Comfortable flip flops made from 100% natural rubber. No synthetic materials or chemicals.',
    price: 22.99,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=300&h=300&fit=crop',
    stock: 140,
    ecoMetrics: {
      materialsScore: 82,
      carbonFootprint: 1.5,
      packagingType: 'minimal',
      manufacturingProcess: 'conventional',
      productLifespan: 24,
      recyclablePercentage: 70,
      biodegradablePercentage: 95,
    },
    sustainabilityGrade: 'B',
    sustainabilityScore: 79,
    seller: {
      name: 'Natural Footwear',
      certifications: ['FSC', 'Fair Rubber'],
    },
    rating: 4.5,
    reviewCount: 321,
  },
  {
    id: '14',
    name: 'Plastic Water Bottle',
    description: 'Standard plastic water bottle. Single-use design.',
    price: 2.99,
    category: 'Sports & Outdoors',
    image: 'https://images.unsplash.com/photo-1536939459926-301728717817?w=300&h=300&fit=crop',
    stock: 500,
    ecoMetrics: {
      materialsScore: 20,
      carbonFootprint: 8.5,
      packagingType: 'plastic',
      manufacturingProcess: 'conventional',
      productLifespan: 0.1,
      recyclablePercentage: 30,
      biodegradablePercentage: 0,
    },
    sustainabilityGrade: 'F',
    sustainabilityScore: 18,
    seller: {
      name: 'Generic Store',
      certifications: [],
    },
    rating: 3.2,
    reviewCount: 89,
  },
  {
    id: '15',
    name: 'Wooden Toy Building Blocks',
    description: 'Set of 50 wooden building blocks made from sustainably sourced wood. Non-toxic paint.',
    price: 34.99,
    category: 'Toys & Games',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=300&fit=crop',
    stock: 70,
    ecoMetrics: {
      materialsScore: 90,
      carbonFootprint: 1.0,
      packagingType: 'paper',
      manufacturingProcess: 'sustainable',
      productLifespan: 120,
      recyclablePercentage: 100,
      biodegradablePercentage: 100,
    },
    sustainabilityGrade: 'A',
    sustainabilityScore: 89,
    seller: {
      name: 'EcoToys Ltd.',
      certifications: ['FSC', 'CE Mark', 'Non-Toxic'],
    },
    rating: 4.8,
    reviewCount: 445,
  },
];

// Helper function to calculate eco-grade from score
export const getEcoGradeColor = (grade) => {
  const gradeColors = {
    'A': '#4CAF50',  // Green
    'B': '#8BC34A',  // Light Green
    'C': '#CDDC39',  // Lime
    'D': '#FFEB3B',  // Yellow
    'E': '#FF9800',  // Orange
    'F': '#F44336',  // Red
  };
  return gradeColors[grade] || '#757575';
};

// Helper function to get eco-grade description
export const getEcoGradeDescription = (grade) => {
  const descriptions = {
    'A': 'Excellent eco-friendly choice',
    'B': 'Very good environmental impact',
    'C': 'Moderate environmental impact',
    'D': 'Below average sustainability',
    'E': 'Poor environmental choice',
    'F': 'Very poor sustainability',
  };
  return descriptions[grade] || 'Unknown';
};

// Filter presets for quick filtering
export const FILTER_PRESETS = {
  ecoFriendly: {
    name: 'Eco-Friendly Only',
    filter: (products) => products.filter(p => ['A', 'B'].includes(p.sustainabilityGrade)),
  },
  bestSellers: {
    name: 'Best Sellers',
    filter: (products) => products.filter(p => p.reviewCount > 300),
  },
  under25: {
    name: 'Under $25',
    filter: (products) => products.filter(p => p.price < 25),
  },
  topRated: {
    name: 'Top Rated',
    filter: (products) => products.filter(p => p.rating >= 4.5),
  },
};

// Sort options for product list
export const SORT_OPTIONS = [
  { label: 'Eco Score (High to Low)', value: 'eco-high' },
  { label: 'Eco Score (Low to High)', value: 'eco-low' },
  { label: 'Price (Low to High)', value: 'price-low' },
  { label: 'Price (High to Low)', value: 'price-high' },
  { label: 'Customer Rating', value: 'rating' },
  { label: 'Most Popular', value: 'popular' },
];